name: just_hook
description: "A lightweight, robust, and structurally complete Flutter Hooks framework inspired by React Hooks. Features state, effect, animation, HTTP, and form management."
version: 0.0.1
homepage: https://github.com/mixin27/just_hook
repository: https://github.com/mixin27/just_hook

topics:
  - hook
  - flutter-hook
  - lightweight

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
